2017-05-19 18:08:26 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Ingredientes_recetas could not be found.
Exception Attributes: array (
  'class' => 'Ingredientes_recetas',
  'plugin' => false,
  'prefix' => false,
  '_ext' => false,
)
Request URL: /ingredientes_recetas
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\ControllerFactory.php(70): Cake\Http\ControllerFactory->missingController(Object(Cake\Http\ServerRequest))
#1 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(90): Cake\Http\ControllerFactory->create(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#2 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\BaseApplication.php(78): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#3 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(59): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#5 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#7 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(92): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\cake\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\Server.php(80): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#14 C:\xampp\htdocs\cake\webroot\index.php(37): Cake\Http\Server->run()
#15 {main}


2017-05-19 18:11:51 Error: Fatal Error (1): Cannot use object of type Cake\ORM\Query as array in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 21]
Request URL: /recetas/add
Referer URL: http://localhost/cake/recetas
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-05-19 18:11:51 Error: [Cake\Error\FatalErrorException] Cannot use object of type Cake\ORM\Query as array in C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp on line 21
Request URL: /recetas/add
Referer URL: http://localhost/cake/recetas
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Cannot use obje...', 'C:\\xampp\\htdocs...', 21)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-05-19 18:14:41 Error: Fatal Error (4): syntax error, unexpected 'echo' (T_ECHO) in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 20]
Request URL: /recetas/add
Referer URL: http://localhost/cake/recetas
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-05-19 18:14:41 Error: [Cake\Error\FatalErrorException] syntax error, unexpected 'echo' (T_ECHO) in C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp on line 20
Request URL: /recetas/add
Referer URL: http://localhost/cake/recetas
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 20)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-05-19 18:18:28 Error: Fatal Error (4): syntax error, unexpected 'echo' (T_ECHO) in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 20]
Request URL: /recetas/add
Referer URL: http://localhost/cake/recetas
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-05-19 18:18:28 Error: [Cake\Error\FatalErrorException] syntax error, unexpected 'echo' (T_ECHO) in C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp on line 20
Request URL: /recetas/add
Referer URL: http://localhost/cake/recetas
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 20)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-05-19 18:22:05 Error: Fatal Error (4): syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']' in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 21]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-05-19 18:22:05 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']' in C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp on line 21
Request URL: /recetas/add
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 21)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-05-19 18:26:39 Error: Fatal Error (1): Cannot use object of type Cake\ORM\Query as array in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 20]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-05-19 18:26:39 Error: [Cake\Error\FatalErrorException] Cannot use object of type Cake\ORM\Query as array in C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp on line 20
Request URL: /recetas/add
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Cannot use obje...', 'C:\\xampp\\htdocs...', 20)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-05-19 18:27:21 Error: Fatal Error (1): Cannot access empty property in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 20]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-05-19 18:27:21 Error: [Cake\Error\FatalErrorException] Cannot access empty property in C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp on line 20
Request URL: /recetas/add
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Cannot access e...', 'C:\\xampp\\htdocs...', 20)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-05-19 18:28:33 Error: Fatal Error (1): Cannot access empty property in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 20]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-05-19 18:28:33 Error: [Cake\Error\FatalErrorException] Cannot access empty property in C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp on line 20
Request URL: /recetas/add
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Cannot access e...', 'C:\\xampp\\htdocs...', 20)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-05-19 18:32:52 Warning: Warning (2): Creating default object from empty value in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 20]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
include - APP/Template\Recetas\add.ctp, line 20
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 1011
Cake\View\View::_render() - CORE\src\View\View.php, line 972
Cake\View\View::render() - CORE\src\View\View.php, line 596
Cake\Controller\Controller::render() - CORE\src\Controller\Controller.php, line 623
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 125
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 93
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 78
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 59
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 92
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
DebugKit\Middleware\DebugKitMiddleware::__invoke() - ROOT\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 80
[main] - ROOT\webroot\index.php, line 37



2017-05-19 18:32:52 Error: Fatal Error (1): Cannot access empty property in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 20]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-05-19 18:32:52 Error: [Cake\Error\FatalErrorException] Cannot access empty property in C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp on line 20
Request URL: /recetas/add
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Cannot access e...', 'C:\\xampp\\htdocs...', 20)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-05-19 18:40:28 Error: Fatal Error (1): Call to a member function get() on integer in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 21]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-05-19 18:40:28 Error: [Cake\Error\FatalErrorException] Call to a member function get() on integer in C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp on line 21
Request URL: /recetas/add
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 21)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-05-19 18:41:48 Error: Fatal Error (1): Call to a member function get() on integer in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 21]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-05-19 18:41:48 Error: [Cake\Error\FatalErrorException] Call to a member function get() on integer in C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp on line 21
Request URL: /recetas/add
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 21)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-05-19 18:42:18 Error: [BadMethodCallException] Unknown method "get"
Request URL: /recetas/add
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\ORM\Query.php(1173): Cake\ORM\Query->_call('get', Array)
#1 C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp(20): Cake\ORM\Query->__call('get', Array)
#2 C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp(20): Cake\ORM\Query->get('nombre')
#3 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\View\View.php(1011): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\View\View.php(972): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#5 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\View\View.php(596): Cake\View\View->_render('C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Controller\Controller.php(623): Cake\View\View->render(NULL, NULL)
#7 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(125): Cake\Controller\Controller->render()
#8 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\RecetasController))
#9 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\BaseApplication.php(78): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#10 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#11 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(59): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#12 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#13 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#14 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#15 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(92): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#17 C:\xampp\htdocs\cake\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#18 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#19 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#20 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\Server.php(80): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#21 C:\xampp\htdocs\cake\webroot\index.php(37): Cake\Http\Server->run()
#22 {main}


2017-05-19 18:58:51 Error: Fatal Error (4): syntax error, unexpected '1' (T_LNUMBER), expecting variable (T_VARIABLE) or '$' in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 20]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-05-19 18:58:51 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '1' (T_LNUMBER), expecting variable (T_VARIABLE) or '$' in C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp on line 20
Request URL: /recetas/add
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 20)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-05-19 18:59:01 Error: Fatal Error (1): Call to a member function get() on null in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 20]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-05-19 18:59:01 Error: [Cake\Error\FatalErrorException] Call to a member function get() on null in C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp on line 20
Request URL: /recetas/add
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 20)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-05-19 18:59:02 Error: Fatal Error (1): Call to a member function get() on null in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 20]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-05-19 18:59:02 Error: [Cake\Error\FatalErrorException] Call to a member function get() on null in C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp on line 20
Request URL: /recetas/add
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 20)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-05-19 18:59:16 Error: Fatal Error (1): Call to a member function get() on null in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 21]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-05-19 18:59:17 Error: [Cake\Error\FatalErrorException] Call to a member function get() on null in C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp on line 21
Request URL: /recetas/add
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 21)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-05-19 18:59:17 Error: Fatal Error (1): Call to a member function get() on null in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 21]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-05-19 18:59:17 Error: [Cake\Error\FatalErrorException] Call to a member function get() on null in C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp on line 21
Request URL: /recetas/add
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 21)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-05-19 19:21:57 Error: Fatal Error (4): syntax error, unexpected end of file in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 28]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-05-19 19:21:57 Error: [Cake\Error\FatalErrorException] syntax error, unexpected end of file in C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp on line 28
Request URL: /recetas/add
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 28)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-05-19 19:22:15 Warning: Warning (2): Invalid argument supplied for foreach() in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 20]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
include - APP/Template\Recetas\add.ctp, line 20
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 1011
Cake\View\View::_render() - CORE\src\View\View.php, line 972
Cake\View\View::render() - CORE\src\View\View.php, line 596
Cake\Controller\Controller::render() - CORE\src\Controller\Controller.php, line 623
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 125
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 93
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 78
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 59
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 92
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
DebugKit\Middleware\DebugKitMiddleware::__invoke() - ROOT\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 80
[main] - ROOT\webroot\index.php, line 37



2017-05-19 19:22:36 Warning: Warning (2): Invalid argument supplied for foreach() in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 20]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
include - APP/Template\Recetas\add.ctp, line 20
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 1011
Cake\View\View::_render() - CORE\src\View\View.php, line 972
Cake\View\View::render() - CORE\src\View\View.php, line 596
Cake\Controller\Controller::render() - CORE\src\Controller\Controller.php, line 623
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 125
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 93
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 78
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 59
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 92
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
DebugKit\Middleware\DebugKitMiddleware::__invoke() - ROOT\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 80
[main] - ROOT\webroot\index.php, line 37



2017-05-19 19:25:34 Error: Fatal Error (4): syntax error, unexpected ')', expecting ']' in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 20]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-05-19 19:25:34 Error: [Cake\Error\FatalErrorException] syntax error, unexpected ')', expecting ']' in C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp on line 20
Request URL: /recetas/add
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 20)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-05-19 19:31:48 Warning: Warning (512): Unable to emit headers. Headers sent in file=C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\Debugger.php line=822 in [C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\ResponseEmitter.php, line 48]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
Cake\Http\ResponseEmitter::emit() - CORE\src\Http\ResponseEmitter.php, line 48
Cake\Http\Server::emit() - CORE\src\Http\Server.php, line 105
[main] - ROOT\webroot\index.php, line 37



2017-05-19 19:31:48 Warning: Warning (2): Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\Debugger.php:822) in [C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\ResponseEmitter.php, line 149]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
header - [internal], line ??
Cake\Http\ResponseEmitter::emitStatusLine() - CORE\src\Http\ResponseEmitter.php, line 149
Cake\Http\ResponseEmitter::emit() - CORE\src\Http\ResponseEmitter.php, line 54
Cake\Http\Server::emit() - CORE\src\Http\Server.php, line 105
[main] - ROOT\webroot\index.php, line 37



2017-05-19 19:31:48 Warning: Warning (2): Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\Debugger.php:822) in [C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\ResponseEmitter.php, line 181]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
header - [internal], line ??
Cake\Http\ResponseEmitter::emitHeaders() - CORE\src\Http\ResponseEmitter.php, line 181
Cake\Http\ResponseEmitter::emit() - CORE\src\Http\ResponseEmitter.php, line 55
Cake\Http\Server::emit() - CORE\src\Http\Server.php, line 105
[main] - ROOT\webroot\index.php, line 37



2017-05-19 19:31:48 Warning: Warning (2): Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\Debugger.php:822) in [C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\ResponseEmitter.php, line 181]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
header - [internal], line ??
Cake\Http\ResponseEmitter::emitHeaders() - CORE\src\Http\ResponseEmitter.php, line 181
Cake\Http\ResponseEmitter::emit() - CORE\src\Http\ResponseEmitter.php, line 55
Cake\Http\Server::emit() - CORE\src\Http\Server.php, line 105
[main] - ROOT\webroot\index.php, line 37



2017-05-19 19:34:35 Warning: Warning (2): Invalid argument supplied for foreach() in [C:\xampp\htdocs\cake\src\Controller\RecetasController.php, line 68]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
App\Controller\RecetasController::add() - APP/Controller\RecetasController.php, line 68
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 440
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 119
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 93
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 78
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 59
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 92
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
DebugKit\Middleware\DebugKitMiddleware::__invoke() - ROOT\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 80
[main] - ROOT\webroot\index.php, line 37



2017-05-19 19:34:35 Warning: Warning (512): Unable to emit headers. Headers sent in file=C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\Debugger.php line=822 in [C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\ResponseEmitter.php, line 48]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
Cake\Http\ResponseEmitter::emit() - CORE\src\Http\ResponseEmitter.php, line 48
Cake\Http\Server::emit() - CORE\src\Http\Server.php, line 105
[main] - ROOT\webroot\index.php, line 37



2017-05-19 19:34:35 Warning: Warning (2): Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\Debugger.php:822) in [C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\ResponseEmitter.php, line 149]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
header - [internal], line ??
Cake\Http\ResponseEmitter::emitStatusLine() - CORE\src\Http\ResponseEmitter.php, line 149
Cake\Http\ResponseEmitter::emit() - CORE\src\Http\ResponseEmitter.php, line 54
Cake\Http\Server::emit() - CORE\src\Http\Server.php, line 105
[main] - ROOT\webroot\index.php, line 37



2017-05-19 19:34:35 Warning: Warning (2): Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\Debugger.php:822) in [C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\ResponseEmitter.php, line 181]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
header - [internal], line ??
Cake\Http\ResponseEmitter::emitHeaders() - CORE\src\Http\ResponseEmitter.php, line 181
Cake\Http\ResponseEmitter::emit() - CORE\src\Http\ResponseEmitter.php, line 55
Cake\Http\Server::emit() - CORE\src\Http\Server.php, line 105
[main] - ROOT\webroot\index.php, line 37



2017-05-19 19:34:35 Warning: Warning (2): Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\Debugger.php:822) in [C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\ResponseEmitter.php, line 181]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
header - [internal], line ??
Cake\Http\ResponseEmitter::emitHeaders() - CORE\src\Http\ResponseEmitter.php, line 181
Cake\Http\ResponseEmitter::emit() - CORE\src\Http\ResponseEmitter.php, line 55
Cake\Http\Server::emit() - CORE\src\Http\Server.php, line 105
[main] - ROOT\webroot\index.php, line 37



2017-05-19 19:36:54 Error: Fatal Error (4): syntax error, unexpected ')' in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 20]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-05-19 19:36:54 Error: [Cake\Error\FatalErrorException] syntax error, unexpected ')' in C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp on line 20
Request URL: /recetas/add
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 20)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-05-19 19:37:08 Error: Fatal Error (4): syntax error, unexpected ')' in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 20]
Request URL: /recetas/add
Referer URL: http://localhost/cake/recetas/
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-05-19 19:37:08 Error: [Cake\Error\FatalErrorException] syntax error, unexpected ')' in C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp on line 20
Request URL: /recetas/add
Referer URL: http://localhost/cake/recetas/
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 20)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-05-19 19:37:16 Error: Fatal Error (4): syntax error, unexpected ')' in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 20]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-05-19 19:37:16 Error: [Cake\Error\FatalErrorException] syntax error, unexpected ')' in C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp on line 20
Request URL: /recetas/add
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 20)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-05-19 19:37:19 Error: Fatal Error (4): syntax error, unexpected ')' in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 20]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-05-19 19:37:19 Error: [Cake\Error\FatalErrorException] syntax error, unexpected ')' in C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp on line 20
Request URL: /recetas/add
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 20)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-05-19 19:41:10 Error: Fatal Error (1): Cannot use object of type Cake\ORM\Query as array in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 21]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-05-19 19:41:10 Error: [Cake\Error\FatalErrorException] Cannot use object of type Cake\ORM\Query as array in C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp on line 21
Request URL: /recetas/add
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Cannot use obje...', 'C:\\xampp\\htdocs...', 21)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-05-19 19:41:28 Error: Fatal Error (1): Cannot access empty property in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 21]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-05-19 19:41:28 Error: [Cake\Error\FatalErrorException] Cannot access empty property in C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp on line 21
Request URL: /recetas/add
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Cannot access e...', 'C:\\xampp\\htdocs...', 21)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-05-19 19:43:53 Error: Fatal Error (4): syntax error, unexpected '=' in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 21]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-05-19 19:43:53 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '=' in C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp on line 21
Request URL: /recetas/add
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 21)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-05-19 19:44:11 Error: Fatal Error (4): syntax error, unexpected '=' in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 21]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-05-19 19:44:11 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '=' in C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp on line 21
Request URL: /recetas/add
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 21)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-05-19 19:45:22 Error: Fatal Error (4): syntax error, unexpected '=' in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 21]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-05-19 19:45:22 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '=' in C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp on line 21
Request URL: /recetas/add
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 21)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-05-19 19:45:28 Error: Fatal Error (4): syntax error, unexpected '=' in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 21]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-05-19 19:45:28 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '=' in C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp on line 21
Request URL: /recetas/add
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 21)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-05-19 19:45:41 Error: Fatal Error (4): syntax error, unexpected '=' in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 21]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-05-19 19:45:41 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '=' in C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp on line 21
Request URL: /recetas/add
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 21)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-05-19 19:45:58 Error: Fatal Error (4): syntax error, unexpected '++' (T_INC) in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 24]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-05-19 19:45:58 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '++' (T_INC) in C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp on line 24
Request URL: /recetas/add
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 24)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-05-19 19:46:35 Error: Fatal Error (4): syntax error, unexpected '++' (T_INC) in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 24]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-05-19 19:46:35 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '++' (T_INC) in C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp on line 24
Request URL: /recetas/add
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 24)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-05-19 19:46:49 Error: Fatal Error (4): syntax error, unexpected '+=' (T_PLUS_EQUAL) in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 24]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-05-19 19:46:49 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '+=' (T_PLUS_EQUAL) in C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp on line 24
Request URL: /recetas/add
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 24)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-05-19 19:58:59 Error: Fatal Error (4): syntax error, unexpected '$i' (T_VARIABLE) in [C:\xampp\htdocs\cake\src\Template\Ingredientes\add.ctp, line 21]
Request URL: /ingredientes/add
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-05-19 19:58:59 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '$i' (T_VARIABLE) in C:\xampp\htdocs\cake\src\Template\Ingredientes\add.ctp on line 21
Request URL: /ingredientes/add
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 21)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-05-19 20:28:27 Warning: Warning (2): Illegal string offset 'nombre' in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 22]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
include - APP/Template\Recetas\add.ctp, line 22
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 1011
Cake\View\View::_render() - CORE\src\View\View.php, line 972
Cake\View\View::render() - CORE\src\View\View.php, line 596
Cake\Controller\Controller::render() - CORE\src\Controller\Controller.php, line 623
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 125
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 93
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 78
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 59
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 92
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
DebugKit\Middleware\DebugKitMiddleware::__invoke() - ROOT\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 80
[main] - ROOT\webroot\index.php, line 37



2017-05-19 20:28:27 Warning: Warning (2): Illegal string offset 'nombre' in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 22]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
include - APP/Template\Recetas\add.ctp, line 22
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 1011
Cake\View\View::_render() - CORE\src\View\View.php, line 972
Cake\View\View::render() - CORE\src\View\View.php, line 596
Cake\Controller\Controller::render() - CORE\src\Controller\Controller.php, line 623
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 125
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 93
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 78
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 59
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 92
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
DebugKit\Middleware\DebugKitMiddleware::__invoke() - ROOT\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 80
[main] - ROOT\webroot\index.php, line 37



2017-05-19 20:28:27 Warning: Warning (2): Illegal string offset 'nombre' in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 22]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
include - APP/Template\Recetas\add.ctp, line 22
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 1011
Cake\View\View::_render() - CORE\src\View\View.php, line 972
Cake\View\View::render() - CORE\src\View\View.php, line 596
Cake\Controller\Controller::render() - CORE\src\Controller\Controller.php, line 623
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 125
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 93
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 78
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 59
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 92
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
DebugKit\Middleware\DebugKitMiddleware::__invoke() - ROOT\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 80
[main] - ROOT\webroot\index.php, line 37



2017-05-19 20:28:27 Warning: Warning (2): Illegal string offset 'nombre' in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 22]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
include - APP/Template\Recetas\add.ctp, line 22
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 1011
Cake\View\View::_render() - CORE\src\View\View.php, line 972
Cake\View\View::render() - CORE\src\View\View.php, line 596
Cake\Controller\Controller::render() - CORE\src\Controller\Controller.php, line 623
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 125
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 93
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 78
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 59
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 92
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
DebugKit\Middleware\DebugKitMiddleware::__invoke() - ROOT\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 80
[main] - ROOT\webroot\index.php, line 37



2017-05-19 20:29:36 Warning: Warning (2): Illegal string offset 'nombre' in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 22]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
include - APP/Template\Recetas\add.ctp, line 22
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 1011
Cake\View\View::_render() - CORE\src\View\View.php, line 972
Cake\View\View::render() - CORE\src\View\View.php, line 596
Cake\Controller\Controller::render() - CORE\src\Controller\Controller.php, line 623
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 125
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 93
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 78
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 59
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 92
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
DebugKit\Middleware\DebugKitMiddleware::__invoke() - ROOT\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 80
[main] - ROOT\webroot\index.php, line 37



2017-05-19 20:29:36 Warning: Warning (2): Illegal string offset 'nombre' in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 22]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
include - APP/Template\Recetas\add.ctp, line 22
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 1011
Cake\View\View::_render() - CORE\src\View\View.php, line 972
Cake\View\View::render() - CORE\src\View\View.php, line 596
Cake\Controller\Controller::render() - CORE\src\Controller\Controller.php, line 623
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 125
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 93
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 78
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 59
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 92
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
DebugKit\Middleware\DebugKitMiddleware::__invoke() - ROOT\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 80
[main] - ROOT\webroot\index.php, line 37



2017-05-19 20:29:36 Warning: Warning (2): Illegal string offset 'nombre' in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 22]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
include - APP/Template\Recetas\add.ctp, line 22
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 1011
Cake\View\View::_render() - CORE\src\View\View.php, line 972
Cake\View\View::render() - CORE\src\View\View.php, line 596
Cake\Controller\Controller::render() - CORE\src\Controller\Controller.php, line 623
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 125
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 93
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 78
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 59
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 92
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
DebugKit\Middleware\DebugKitMiddleware::__invoke() - ROOT\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 80
[main] - ROOT\webroot\index.php, line 37



2017-05-19 20:29:36 Warning: Warning (2): Illegal string offset 'nombre' in [C:\xampp\htdocs\cake\src\Template\Recetas\add.ctp, line 22]
Request URL: /recetas/add
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
include - APP/Template\Recetas\add.ctp, line 22
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 1011
Cake\View\View::_render() - CORE\src\View\View.php, line 972
Cake\View\View::render() - CORE\src\View\View.php, line 596
Cake\Controller\Controller::render() - CORE\src\Controller\Controller.php, line 623
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 125
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 93
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 78
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 59
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 92
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
DebugKit\Middleware\DebugKitMiddleware::__invoke() - ROOT\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 80
[main] - ROOT\webroot\index.php, line 37



2017-05-23 01:00:19 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Js could not be found.
Exception Attributes: array (
  'class' => 'Js',
  'plugin' => false,
  'prefix' => false,
  '_ext' => false,
)
Request URL: /js/jquery-1.4.2.min.js
Referer URL: http://localhost/cake/ingredientes
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\ControllerFactory.php(70): Cake\Http\ControllerFactory->missingController(Object(Cake\Http\ServerRequest))
#1 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(90): Cake\Http\ControllerFactory->create(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#2 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\BaseApplication.php(78): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#3 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(59): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#5 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(93): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#7 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(92): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\cake\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\Server.php(80): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#14 C:\xampp\htdocs\cake\webroot\index.php(37): Cake\Http\Server->run()
#15 {main}


2017-05-23 02:32:59 Error: Fatal Error (4): syntax error, unexpected 'asc' (T_STRING), expecting ')' in [C:\xampp\htdocs\cake\src\Controller\IngredientesController.php, line 27]
Request URL: /ingredientes
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-05-23 02:32:59 Error: [Cake\Error\FatalErrorException] syntax error, unexpected 'asc' (T_STRING), expecting ')' in C:\xampp\htdocs\cake\src\Controller\IngredientesController.php on line 27
Request URL: /ingredientes
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 27)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-05-23 02:35:30 Error: [Cake\Routing\Exception\MissingRouteException] A route matching "/" could not be found.
Exception Attributes: array (
  'url' => '/',
)
Request URL: /
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Router.php(368): Cake\Routing\RouteCollection->parseRequest(Object(Cake\Http\ServerRequest))
#1 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(48): Cake\Routing\Router::parseRequest(Object(Cake\Http\ServerRequest))
#2 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#3 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#4 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#5 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(92): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#6 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#7 C:\xampp\htdocs\cake\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#8 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#9 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#10 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\Server.php(80): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 C:\xampp\htdocs\cake\webroot\index.php(37): Cake\Http\Server->run()
#12 {main}


2017-05-23 02:35:40 Error: [Cake\Routing\Exception\MissingRouteException] A route matching "/" could not be found.
Exception Attributes: array (
  'url' => '/',
)
Request URL: /
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Router.php(368): Cake\Routing\RouteCollection->parseRequest(Object(Cake\Http\ServerRequest))
#1 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(48): Cake\Routing\Router::parseRequest(Object(Cake\Http\ServerRequest))
#2 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#3 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#4 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#5 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(92): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#6 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#7 C:\xampp\htdocs\cake\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#8 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#9 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#10 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\Server.php(80): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 C:\xampp\htdocs\cake\webroot\index.php(37): Cake\Http\Server->run()
#12 {main}


2017-05-23 02:35:52 Error: [Cake\Controller\Exception\MissingActionException] Action RecetasController::display() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'RecetasController',
  'action' => 'display',
  'prefix' => '',
  'plugin' => false,
)
Request URL: /
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(119): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\RecetasController))
#2 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\BaseApplication.php(78): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#3 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(59): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#5 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#7 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(92): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\cake\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Http\Server.php(80): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#14 C:\xampp\htdocs\cake\webroot\index.php(37): Cake\Http\Server->run()
#15 {main}


